[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.build-webd]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["logic"] }
script = '''
cd crates/logic && wasm-pack build --target web -d ../web/public/pkg
'''

[tasks.build-webr]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["logic"] }
script = '''
cd crates/logic && wasm-pack build --release --target web -d ../web/public/pkg
'''

[tasks.webd]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["web"], CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
dependencies = ["build-webd"]
script = '''
cd crates/web && cargo run
'''

[tasks.webr]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["web"], CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
dependencies = ["build-webr"]
script = '''
cd crates/web && cargo run --release
'''